version: "3.2"

services:
  traefik:
    image: traefik:1.7-alpine
    container_name: traefik
    command:
      - "--logLevel=INFO"
      - "--defaultentrypoints=http,https"
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--docker"
      - "--docker.exposedbydefault=false"
      - "--docker.domain=example.com"
      - "--acme=true"
      - "--acme.acmelogging=true"
      - "--acme.email=webmaster@example.com"
      - "--acme.storage=acme.json"
      - "--acme.entryPoint=https"
      - "--acme.onhostrule=true"
      - "--acme.httpchallenge=true"
      - "--acme.httpchallenge.entrypoint=http"
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  db:
    image: mariadb:10.2
    container_name: matomo_db
    volumes:
      - "db:/var/lib/mysql"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=matomo"
      - "MYSQL_USER=matomo"
      - "MYSQL_PASSWORD=asupersecretpassword"
    restart: always

  redis:
    image: redis:4.0-alpine
    container_name: matomo_redis
    restart: always

  matomo:
    image: crazymax/matomo:latest
    container_name: matomo
    depends_on:
      - db
      - redis
    volumes:
      - "matomo:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=matomo"
      - "traefik.port=8000"
      - "traefik.frontend.rule=Host:matomo.example.com"
    env_file:
      - "./matomo.env"
    restart: always

  cron:
    image: crazymax/matomo:latest
    container_name: matomo_cron
    depends_on:
      - matomo
    volumes:
      - "matomo:/data"
    env_file:
      - "./matomo.env"
    environment:
      - "SIDECAR_CRON=1"
      - "CRON_GEOIP=0 2 * * *"
      - "CRON_ARCHIVE=0 * * * *"
      - "ARCHIVE_OPTIONS=--concurrent-requests-per-website=3"
    restart: always

volumes:
  db:
  matomo:
